### ISSUE TITLE
About test on Flickr1024 dataset for 2x SR

### ISSUE THREAD

**Issue by 123abcgit** [YingqianWang/iPASSR#3]
Hi, thanks for your sharing! I want to test iPASSR_2x.pth on the Flickr1024 dateset for 2x SR  using the test.py  provided in iPASSR and demo_test.py provided by PASSRnet on a PC with NVIDIA GeForce RTX 3090. But it is always out of memory, is there any way to solve it? Looking forward to your reply. Thank you very much!

**Comment by YingqianWang** [comment]
Thanks for your attention. Since some images in the Flickr1024 dataset are of very high resolutions, directly performing inference on these images will result in an out-of-memorty problem. Two solutions can be considered to solve this issue:
(1) Perform test on CPUs. We adopted this strategy to perform test in our iPASSR paper.
(2) Crop input images into patches with overlaps and perform inference on these patchese seperately. Finally, integrate these patches to produce the final images. We do not have the codes for cropping and integration yet.
